### ISSUE TITLE
Add dynamic theme change (windows 10)

### ISSUE THREAD

**Issue by suratovvlad** [suratovvlad/qBittorrent#2]
**Please provide the following information**
There is a suggestion from @mo0nsniper in [official dark theme request](https://github.com/qbittorrent/qBittorrent/issues/6434) to use Windows 10 Theme settings (toggle mode from dark to light and back to dark).

**Comment by suratovvlad** [comment]
It is possible to do, I've already implemented it in [libqdark](https://github.com/suratovvlad/libqdark), however qbittorent crashes as described [here](https://github.com/suratovvlad/libqdark/issues/6)

**Comment by mo0nsniper** [comment]
This is great news, hope you manage to get it working.

**Comment by suratovvlad** [comment]
Done, check qbittorrent-installer to get new release

**Comment by alvgalrus** [comment]
Why not sending a PR to the official qBittorrent repo? I'd rather have this theme as a native feature!
