### ISSUE TITLE
Ubuntu Build

### ISSUE THREAD

**Issue by melroy89** [suratovvlad/qBittorrent#3]
### qBittorrent version and Operating System
Linux Mint 20 (Ubuntu Focal 20.04)

### If on linux, libtorrent-rasterbar and Qt version

* libtorrent-rasterbar10 (1.2.12+git20210118.3efdb8a941-1ppa1~20.04)
* qt5 (5.12.8)

### What is the problem
Executing the exectable from the GH Actions build (for Ubuntu 20) gives me:

```
./qbittorrent: symbol lookup error: ./qbittorrent: undefined symbol: _ZNK10libtorrent14torrent_handle11add_trackerERKNS_4v1_214announce_entryE
```

### What is the expected behavior
No missing symbols.

### Steps to reproduce
1. Download the artifact
2. `chmod +x ./qbittorrent`
3. Try to execute the binary: `./qbittorrent`

Regards,
Melroy

**Comment by suratovvlad** [comment]
Hi Melroy!

Actually, I'm not sure is it a good idea to take artifacts from GA Actions:
* These actions were created by original repo holder, so I know almost nothing about them
* Builds are not stable - only master branch is built, not a release version
* Builds do not contain changes I've made for the dark theme

On the one hand, what I see on actions page, that my master branch from Jan 2021 uses libtorrent 1.2.11, so probably your version is much newer.

On the other hand, I see, that github actions CI builds own libtorrent first and in the end publishes static compiled version of qbittorrent, so it would be natural to expect that libtorrent symbols are included to the binary, so it is strange indeed.

If you are interested in dark theme features, you need to clone my repo, switch to release-X.X.X-dark branch (optional) and build your own version of qbittorrent. Most likely you also need to build own libtorrent version.

Unfortunately I don't have a time and wish to support builds for any other distributives, except archlinux and manjaro.
Maybe one day I will configure github actions for my branch, but I need to think about it
